version: 1.0.{build}
image: Visual Studio 2022
before_build:
- ps: >-
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"; & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '6.0.100-rc.2.21505.57' -InstallDir "$env:ProgramFiles\dotnet"
- dotnet restore
- dotnet clean
- dotnet build
- dotnet publish -p:PublishProfile=./FolderProfile.pubxml
#- dotnet publish -p:TargetFramework=net6.0 -p:RuntimeIdentifier=win-x64 -p:SelfContained=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=embedded -p:ServerGarbageCollection=true --output .\bin\Release\net6.0\publish\win-x64\
#- dotnet publish --arch x64 --configuration Release --framework net6.0 --self-contained true /p:PublishSingleFile=true
nuget:
  project_feed: true
deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/nstevens1040/index.json
    artifact: ./AngleSharpParser/bin/Release/net6.0/publish/win-x64/
    username: nstevens1040
    api_key:
      secure: f+MLRpFFOj9kyNxbFyIt2n5I/dR48bmJ6qXRB/ageJ/18o61FDhu61IZgwk9KfqD
artifacts:
  - path: AngleSharpParser.1.0.{build}.nupkg
    name: AngleSharpParser
    type: File
after_build:
- ps: >-
    if(get-childitem -Recurse -Path C:\projects\anglesharpparser\AngleSharpParser\bin\Release | ? {$_.Extension -eq ".nupkg"}){ get-childitem -Recurse -Path C:\projects\anglesharpparser\AngleSharpParser\bin\Release | ? {$_.Extension -eq ".nupkg"} | % { write-host $_.FullName -ForeGroundColor Yellow }} else { write-host "no nupkg found" -ForegroundColor Yellow }; if(get-childitem -Path C:\projects\anglesharpparser\AngleSharpParser\bin\Release\net6.0\publish\win-x64\){ get-childitem -Path C:\projects\anglesharpparser\AngleSharpParser\bin\Release\net6.0\publish\win-x64\ | % { write-host $_.FullName -ForegroundColor Green } else { write-host "no files in bin\Release\net6.0\publish\win-x64" -ForegroundColor green }
